# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 880f3b188e9b405226cea965dd3f41fadff9556005ee1a0cfbe4007db58fe18f1b952548a7eef53d9360768f47bdf0aae1f55581e2a3e9813d1a8ac801f1fd0e

test:
  secret_key_base: 4c4f9505331bb881cf2ab9b64286a3ae62a9f65f0670c2eeddc81294142b6d149e64c4bf6a69090f1dd9b02088a3242ce363e34752fbeac1c37bc223ae7e3153

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
